models:
  minicnn_small:
    name: "MiniCNN"

    params:
      in_channels: 3
      num_classes: 10
      activation: "relu"
      classifier_hidden_dims: [128]

      conv_channels: [32, 64, 128]

      conv_defaults:
        kernel_size: 3
        stride: 1
        padding: 1
        use_batch_norm: true
        use_max_pool: true
        use_skip_connection: false

  minicnn_medium:
    name: "MiniCNN"

    params:
      in_channels: 3
      num_classes: 10
      activation: "relu"
      classifier_hidden_dims: [256]

      conv_channels: [32, 64, 128, 256]

      conv_defaults:
        kernel_size: 3
        stride: 1
        padding: 1
        use_batch_norm: true
        use_max_pool: true
        use_skip_connection: false

  minicnn_large:
    name: "MiniCNN"

    params:
      in_channels: 3
      num_classes: 10
      activation: "relu"
      classifier_hidden_dims: [512, 256]

      conv_channels: [64, 128, 256, 512]

      conv_defaults:
        kernel_size: 3
        stride: 1
        padding: 1
        use_batch_norm: true
        use_max_pool: true
        use_skip_connection: true